### ISSUE TITLE
Let empty items, empty categories, etc.

### ISSUE THREAD

**Issue by gjuchault** [buckless-team/admin#188]
![image](https://user-images.githubusercontent.com/678848/27221394-bbb51862-5288-11e7-887b-f9d4713cf358.png)

![image](https://user-images.githubusercontent.com/678848/27221404-c1a85248-5288-11e7-9e88-fca20a50965c.png)

Let the title be, with "No items currently"

**Comment by lonk** [comment]
Fixed by #219
