### ISSUE TITLE
Requests not submitted

### ISSUE THREAD

**Issue by BeauneNuits** [buckless-team/admin#225]
Some requests never reach the server, e.g. a point's creation, and the admin interface displays an error message : "Le point ____ n'a pas pu être créé".
This also happens for other requests, randomly.

**Comment by lonk** [comment]
I have not succeeded in reproducing this issue. Are you sure that it isn't network related ?

**Comment by BeauneNuits** [comment]
Could be, although if you use TCP as transport layer, the failure rate would be alarmingly high, and should have an impact on every other network services, which it does not.
